INSERT INTO Book (title, author, publicationYear) VALUES
('The Shining', 'Stephen King', 1977),
('Dracula', 'Bram Stoker', 1897),
('Frankenstein', 'Mary Shelley', 1818),
('The Haunting of Hill House', 'Shirley Jackson', 1959),
('Pet Sematary', 'Stephen King', 1983),
('Gone Girl', 'Gillian Flynn', 2012),
('The Girl on the Train', 'Paula Hawkins', 2015),
('Behind Closed Doors', 'B.A. Paris', 2016),
('The Silent Patient', 'Alex Michaelides', 2019),
('Sharp Objects', 'Gillian Flynn', 2006),
('The Hound of the Baskervilles', 'Arthur Conan Doyle', 1902),
('And Then There Were None', 'Agatha Christie', 1939),
('The Maltese Falcon', 'Dashiell Hammett', 1929),
('Double Indemnity', 'James M. Cain', 1943),
('The Postman Always Rings Twice', 'James M. Cain', 1934),
('Rebecca', 'Daphne du Maurier', 1938),
('The Turn of the Screw', 'Henry James', 1898),
('Strangers on a Train', 'Patricia Highsmith', 1950),
('The Talented Mr. Ripley', 'Patricia Highsmith', 1955),
('The Woman in White', 'Wilkie Collins', 1859),
('Wuthering Heights', 'Emily Brontë', 1847),
('The Strange Case of Dr Jekyll and Mr Hyde', 'Robert Louis Stevenson', 1886),
('The Picture of Dorian Gray', 'Oscar Wilde', 1890),
('Jane Eyre', 'Charlotte Brontë', 1847),
('The Castle of Otranto', 'Horace Walpole', 1764);